// <reference types="cypress"/>
const getvalue=require('../fixtures/data.json')

const acc=require('../fixtures/account.json')
export class Account{

signin(email,password)
{
    cy.log('**[ Checking Sign In with a valid case ]()**')
    cy.xpath("//div[@title='My Account']").click({force:true})
    cy.contains('Sign In').click({force:true})
    cy.get('#email').click().type(email)
    cy.get('#pass').click().type(password)
    cy.get('#send2').click({force:true})

}
createAccount(emailaddress,password,firstname,lastname)
{

    cy.log('**[ Creating account with a valid case ]()**')
    cy.xpath("//div[@title='My Account']").click({force:true})
   cy.contains('Create an Account').click()
   cy.url().should('equal','https://pk.khaadi.com/customer/account/create/')

   cy.get('#firstname').click().type(firstname)
   cy.get('#lastname').click().type(lastname)
   cy.get('#email_address').click().type(emailaddress)
   cy.get('#password').click().type(password)
   cy.get('#password-confirmation').click().type(password)
   cy.log("Perform Robot Activity")
   cy.wait(40000)
   cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
   cy.url().should('equal','https://pk.khaadi.com/customer/account/')
   cy.get('.message-success').should('be.visible')
   cy.xpath("//div[@title='My Account']").click({force:true})
   cy.get('.items > :nth-child(4) > a').click({force:true})
   cy.wait(5000)

cy.get('.base').should('contain.text','Add New Address')
cy.get('#telephone').click().type('03458417111')
cy.get('#street_1').click().type('54 T DHA')
cy.get('#region_id').select('610')
cy.get('#saveAddressButton').click({force:true})
    cy.contains('Sign Out').click({force:true})
    cy.wait(5000)
}
myaccount()
{
    cy.log('**[Going To My Account ]()**')
cy.xpath("//div[@title='My Account']").click({force:true})
cy.contains('My Account').click({force:true})
cy.url().should('equal','https://pk.khaadi.com/customer/account/')

cy.log('**[ My Account Main Page]()**')
cy.get('.page-title-wrapper').should('be.visible').should('contain.text','My Account')
cy.get('.block-dashboard-info > .block-title > strong').should('have.text','Account Information')
cy.get('.block-dashboard-info > .block-content').should('be.visible')
cy.get('.box-information').should('be.visible')
cy.get('.box-information > .box-title').should('have.text','Contact Information')
cy.get('.box-information > .box-content > p').should('not.be.empty')
cy.get('.box-information > .box-actions').should('be.visible')
cy.get('.box-information > .box-actions > .edit').should('be.visible').click()
cy.url().should('equal','https://pk.khaadi.com/customer/account/edit/')
cy.go('back')
cy.get('.change-password').should('be.visible').click()
cy.url().should('include','https://pk.khaadi.com/customer/account/edit/changepass/')
cy.go('back')
cy.get('.box-newsletter > .box-title').should('have.text','Newsletters')
cy.get('.box-newsletter > .box-content').should('not.be.empty')
cy.get('.box-newsletter > .box-actions').should('be.visible')
cy.get('.box-newsletter > .box-actions > .action > span').should('be.visible').click()
cy.url().should('equal','https://pk.khaadi.com/newsletter/manage/')
cy.go('back')

cy.get('.block-dashboard-addresses').should('be.visible')
cy.get('h3 > span').should('have.text','Address Book')
cy.get('.box-billing-address > .account-sub-title').should('have.text','Default Billing Address')
cy.get('.box-billing-address > .box-content > address').should('be.visible').should('not.be.empty')
cy.get('.box-billing-address > .box-actions').should('be.visible')
cy.get('.box-billing-address > .box-actions > .action').should('be.visible').click()
cy.url().should('include','https://pk.khaadi.com/customer/address/edit/')
cy.go('back')
cy.get('.box-shipping-address > .account-sub-title').should('have.text','Default Shipping Address')
cy.get('.box-shipping-address > .box-content > address').should('be.visible').should('not.be.empty')
cy.get('.box-shipping-address > .box-actions').should('be.visible')
cy.get('.box-shipping-address > .box-actions > .action').should('be.visible').click()
cy.url().should('include','https://pk.khaadi.com/customer/address/edit')
cy.go('back')
cy.log('**[ My Orders Page]()**')
cy.get('.items > :nth-child(2) > a').click()
cy.get('.page-title-wrapper').should('be.visible').should('contain.text','My Orders')


cy.log('**[Address Book Page]()**')
cy.get('.items > :nth-child(4) > a').click({force:true})
cy.url().should('equal','https://pk.khaadi.com/customer/address/')
cy.get('.base').should('contain.text','Address Book')
cy.get('.block-addresses-default > .block-content').should('be.visible')
cy.get('.box-address-billing').should('be.visible')
cy.get('.box-address-billing > .box-title').should('contain.text','Default Billing Address')
cy.get('.box-address-billing > .box-content > address').should('be.visible')
cy.get('.box-address-billing > .box-actions').should('contain.text','Change Billing Address')
cy.get('.box-address-shipping').should('be.visible')
cy.get('.box-address-shipping > .box-title').should('contain.text','Default Shipping Address')
cy.get('.box-address-shipping > .box-content > address').should('be.visible')
cy.get('.box-address-shipping > .box-actions').should('contain.text','Change Shipping Address')
cy.get('.block-addresses-list > .block-title > strong').should('contain.text','Additional Address Entries')
cy.get('.block-addresses-list > .block-content > .empty').should('contain.text','You have no other address entries in your address book.')


cy.log('**[Adding New Address]()**')
cy.wait(5000)
cy.xpath("//button[@role='add-address']").should('contain.text','Add New Address').click({force:true})
cy.get('.base').should('contain.text','Add New Address')
cy.get('#telephone').click().type('03458417111')
cy.get('#street_1').click().type('54 T DHA')
cy.get('#region_id').select('610')
cy.get('#saveAddressButton').click({force:true})
cy.url().should('equal','https://pk.khaadi.com/customer/address/index/')
cy.wait(5000)
cy.get('.message-success').should('be.visible')
cy.get('.message-success > div').should('contain.text','You saved the address.')

cy.log('**[ Verifying Additional Address Table ]()**')
cy.get('.block-addresses-list > .block-content').should('be.visible')
cy.get('thead > tr').should('be.visible')
cy.get('thead > tr > .firstname').should('contain.text','First Name')
cy.get('thead > tr > .lastname').should('contain.text','Last Name')
cy.get('thead > tr > .streetaddress').should('contain.text','Street Address')
cy.get('thead > tr > .city').should('contain.text','City')
cy.get('thead > tr > .country').should('contain.text','Country')
cy.get('thead > tr > .state').should('contain.text','State')
cy.get('thead > tr > .zip').should('contain.text','Zip/Postal Code')
cy.get('thead > tr > .phone').should('contain.text','Phone')
cy.get('thead > tr > .actions').should('be.visible')
cy.get('tbody > tr > .firstname').should('not.be.empty')
cy.get('tbody > tr > .lastname').should('not.be.empty')
cy.get('tbody > tr > .streetaddress').should('not.be.empty')
cy.get('tbody > tr > .city').should('not.be.empty')
cy.get('tbody > tr > .country').should('not.be.empty')
cy.get('tbody > tr > .state').should('not.be.empty')
cy.get('tbody > tr > .zip').should('be.empty')
cy.get('tbody > tr > .phone').should('not.be.empty')
cy.get('tbody > tr > .actions').should('be.visible')
cy.log('**[ Editing Address ]()**')
cy.get('.actions > .edit').should('be.visible').click({force:true})
cy.url().should('contain','https://pk.khaadi.com/customer/address/edit')

//cy.get('#city').select('Lahore')
/*cy.get('#primary_billing').click()
cy.get('#primary_shipping').click()
cy.get('#saveAddressButton').click({force:true})*/

cy.go('back')
cy.wait(5000)

cy.log('**[ Deleting Address ]()**')
cy.get('.delete').click({force:true})
cy.get('.confirm > .modal-inner-wrap > .modal-header').should('be.visible')
//cy.get('#modal-content-16 > div').should('contain.text','Are you sure you want to delete this address?')
cy.get('.action-secondary').should('be.visible').should('contain.text','Cancel')
cy.get('.action-primary').should('be.visible').should('contain.text','OK').click()
cy.wait(5000)
cy.get('.message-success').should('be.visible')
cy.get('.message-success > div').should('have.text','You deleted the address.')

cy.log('**[ Going to Account Information ]()**')
cy.get('.items > :nth-child(5) > a').click({force:true})
cy.url().should('contain','https://pk.khaadi.com/customer/account/edit/')
cy.get('.base').should('contain.text','Edit Account Information')
cy.get('.info').should('be.visible')
cy.get('.info > .legend > span').should('contain.text','Account Information')
cy.get('.field-name-firstname > .label > span').should('contain.text','First Name')
cy.get('#firstname').click().clear().type('Hifsa')
cy.get('.field-name-lastname > .label > span').should('contain.text','Last Name')
cy.get('#lastname').click().clear().type('Khan')
cy.get('#form-validate > .actions-toolbar > div.primary > .action').click({force:true})
cy.wait(5000)
cy.get('.message-success').should('be.visible')
cy.get('.message-success > div').should('have.text','You saved the account information.')


cy.log('**[ Change Email ]()**')
cy.get('.items > :nth-child(5) > a').click({force:true})
cy.get('#change-email').click()
cy.get('.fieldset.password').should('be.visible')
cy.get('.fieldset.password > .legend').should('contain.text','Change Email')
cy.get('.fieldset.password > .email > .label > span').should('contain.text','Email')
cy.get('#email').click().clear().type(acc.email)
cy.get('.current > .label').should('contain.text','Current Password')
cy.get('#current-password').should('be.visible').click().clear().type(acc.password)
cy.get('#form-validate > .actions-toolbar > div.primary > .action').click({force:true})
//cy.url().should('equal','https://pk.khaadi.com/customer/account/')
cy.get('.message-success').should('be.visible')
cy.get('.message-success > div').should('have.text','You saved the account information.')
this.signin(acc.email,acc.password)

cy.log('**[ Change Password ]()**')
cy.get('.items > :nth-child(5) > a').click({force:true})
cy.url().should('contain','https://pk.khaadi.com/customer/account/edit/')
cy.get('#change-password').click()
cy.get('.fieldset.password').should('be.visible')
cy.get('.fieldset.password > .legend > span').should('have.text','Change Password')
cy.get('.current > .label').should('have.text','Current Password')
cy.get('#current-password').should('be.visible').click().type(acc.password)
cy.get('.new > .label > span').should('have.text','New Password')
cy.get('#password').click().type(acc.newpassword)
cy.get('#password-strength-meter').should('be.visible')
cy.get('.confirm > .label').should('be.visible').should('have.text','Confirm New Password')
cy.get('#password-confirmation').click().type(acc.newpassword)
cy.get('#form-validate > .actions-toolbar > div.primary > .action').click({force:true})
cy.get('.message-success').should('be.visible')
cy.get('.message-success > div').should('have.text','You saved the account information.')
this.signin(acc.email,acc.newpassword)

cy.log('**[ Change Email & Password ]()**')
cy.get('.items > :nth-child(5) > a').click({force:true})
cy.url().should('contain','https://pk.khaadi.com/customer/account/edit/')
cy.get('#change-email').click({force:true})
cy.get('#change-password').click({force:true})
cy.get('.fieldset.password').should('be.visible')
cy.get('.fieldset.password > .legend > span').should('have.text','Change Email and Password')
cy.get('.fieldset.password > .email > .label > span').should('have.text','Email')
cy.get('#email').click().clear().type(acc.email)
cy.get('.current > .label > span').should('have.text','Current Password')
cy.get('#current-password').click().type(acc.newpassword)
cy.get('.new > .label').should('have.text','New Password')
cy.get('#password').click().type(acc.newpasswordemail)
cy.get('#password-strength-meter').should('be.visible')
cy.get('.confirm > .label').should('be.visible').should('have.text','Confirm New Password')
cy.get('#password-confirmation').click().type(acc.newpasswordemail)
cy.get('#form-validate > .actions-toolbar > div.primary > .action').click({force:true})
cy.get('.message-success').should('be.visible')
cy.get('.message-success > div').should('have.text','You saved the account information.')
this.signin(acc.email,acc.newpasswordemail)


cy.log('**[ Going to Newsletter Subscription Page ]()**')
cy.get('.items > :nth-child(7) > a').click({force:true})
cy.url().should('equal','https://pk.khaadi.com/newsletter/manage/')
cy.get('.base').should('have.text','Newsletter Subscription')
cy.get('.legend > span').should('have.text','Subscription option')
cy.get('#form-validate > .fieldset > .field > .label > span').should('be.visible').should('have.text','General Subscription')
cy.get('#subscription').should('be.visible').click()
cy.get('#form-validate > .actions-toolbar > div.primary > .action').click({force:true})
cy.wait(5000)
cy.get('.message-success').should('be.visible')
cy.get('.message-success > div').should('have.text','A confirmation request has been sent.')

cy.log('**[ Going to My Returns Page ]()**')
cy.get('.items > :nth-child(8) > a').click()
cy.url().should('equal','https://pk.khaadi.com/rma/returns/history/')
cy.get('.base').should('have.text','My Returns')
cy.contains('Sign Out').click({force:true})
    cy.wait(5000)
}




}
